version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: Mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: digipank
      MYSQL_USER: bankuser
      MYSQL_PASSWORD: bankpass
    ports:
      - "3309:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./sql-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mariadb-data:
   
